saving and loading codemaps
rohanadwankar@Rohans-MacBook-Pro oxdraw % cargo run -- --code-map src/ -o oxdraw_src_map.mmd
   Compiling oxdraw v0.1.2 (/Users/rohanadwankar/oxdraw)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.68s
     Running `target/debug/oxdraw --code-map src/ -o oxdraw_src_map.mmd`
Scanning codebase at /Users/rohanadwankar/oxdraw/src...
Found 7 files. Generating code map...
Code map saved to oxdraw_src_map.mmd
rohanadwankar@Rohans-MacBook-Pro oxdraw % cargo run -- --edit oxdraw_src_map.mmd
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/oxdraw --edit oxdraw_src_map.mmd`
error: unexpected argument 'oxdraw_src_map.mmd' found

Usage: oxdraw [OPTIONS]

For more information, try '--help'.
rohanadwankar@Rohans-MacBook-Pro oxdraw % cargo run -- --input oxdraw_src_map.mmd
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/oxdraw --input oxdraw_src_map.mmd`
Generated diagram -> oxdraw_src_map.mmd.svg
rohanadwankar@Rohans-MacBook-Pro oxdraw % open oxdraw_src_map.mmd.svg
rohanadwankar@Rohans-MacBook-Pro oxdraw % cargo run -- --input oxdraw_src_map.mmd --edit
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/oxdraw --input oxdraw_src_map.mmd --edit`
Launching editor for /Users/rohanadwankar/oxdraw/oxdraw_src_map.mmd
Loaded web UI from /var/folders/qw/24v8bc0x6x30513s6npnt5jw0000gn/T/oxdraw-ui/0.1.2
Visit http://127.0.0.1:5151 in your browser to begin editing
error: failed to bind HTTP server to 127.0.0.1:5151

Caused by:
    Address already in use (os error 48)
rohanadwankar@Rohans-MacBook-Pro oxdraw % cargo run -- --input oxdraw_src_map.mmd --edit
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/oxdraw --input oxdraw_src_map.mmd --edit`
Launching editor for /Users/rohanadwankar/oxdraw/oxdraw_src_map.mmd
Loaded web UI from /var/folders/qw/24v8bc0x6x30513s6npnt5jw0000gn/T/oxdraw-ui/0.1.2
Visit http://127.0.0.1:5151 in your browser to begin editing
oxdraw server listening on http://127.0.0.1:5151
Press Ctrl+C to stop.
^C%                                                                                                                                     rohanadwankar@Rohans-MacBook-Pro oxdraw % mv oxdraw_src_map.mmd tests/input/oxdraw_src_map.mmd